permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Vanxin
  email: vanxinliu@gmail.com
  link: http://ivanxin.com
  weibo: http://weibo.com/vanxinliu
  github: http://github.com/vanxin

# 站点信息
title: Vanxin's Blog 
description: Vanxin's Blog 
url: http://ivanxin.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.png
favicon: /public/upload/gavatar/favicon.ico

# google analytics 设置
ga:
  id: UA-43667383-1
  url: ivanxin.com

# disqus 设置
disqus:
  shortname: VanxinLiu

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
